# Имя проекта
name: blas_project

# Список сервисов (контейнеров)
services:
  # Сервис для тестирования BLAS
  blas_test:
    # Собираем образ из Dockerfile в текущей директории (.)
    build: .
    
    # Монтируем папки (пробрасываем файлы между хостом и контейнером)
    volumes:
      # Это нужно, чтобы БД сохранялась после остановки контейнера
      - ./database:/data